#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
fi

export RAILS_ENV=test

exit_code=0

function run {
    declare -a tests_command=("$@")
    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

# (re)install node packages to local dir before tests run
run ./bin/setup
run bundle exec rspec

exit "$exit_code"
